Repository AY2223S2-CS2103T-T15-2/tp, pull requests merged in 2023-03, with the labels that each got.

#76 Update UG
  docs/UserGuide.md
Labels: documentation

#79 Branch update DG
  docs/DeveloperGuide.md
  gradle.properties
Labels: documentation

#82 Update DG and own md
  docs/DeveloperGuide.md
  docs/team/jundatan.md
Labels: documentation

#85 Update DG -Kalaris
  docs/DeveloperGuide.md
Labels: documentation

#57 Branch add Gender and Weight class (Can merge)
  docs/DeveloperGuide.md
  docs/team/dfordarius.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/FitBookModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Gender.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/client/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonFitBookStorageTest/invalidAndValidClientFitBook.json
  src/test/data/JsonSerializableFitBookTest/duplicateClientFitBook.json
  src/test/data/JsonSerializableFitBookTest/invalidClientFitBook.json
  src/test/data/JsonSerializableFitBookTest/typicalClientsFitBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/GenderTest.java
  src/test/java/seedu/address/model/client/WeightTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: enhancement

#77 Branch add calorie (Can merge)
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Calorie.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableFitBookTest/duplicateClientFitBook.json
  src/test/data/JsonSerializableFitBookTest/typicalClientsFitBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/CalorieTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: type.Enhancement

#88 Branch update UI jh
  src/main/java/seedu/address/logic/commands/ListClientsCommand.java
  src/main/java/seedu/address/logic/parser/FitBookParser.java
  src/main/java/seedu/address/model/FitBookModel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/font/Aclonica-Regular.ttf
  src/main/resources/font/Inter-VariableFont_slnt,wght.ttf
  src/main/resources/font/LaBelleAurore-Regular.ttf
  src/main/resources/font/LakkiReddy-Regular.ttf
  src/main/resources/font/LeckerliOne-Regular.ttf
  src/main/resources/images/FitBook.png
  src/main/resources/images/FitnessG.png
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/FitBook.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListClientsCommandTest.java
  src/test/java/seedu/address/logic/parser/FitBookParserTest.java
Labels: type.Enhancement

#91 Branch update UI jh
  src/main/resources/images/address_book_32.png
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement

#93 Add shadows to UI and fix a minor issue
  docs/DeveloperGuide.md
  docs/team/jundatan.md
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
Labels: UI

#95 Fix UI
  src/main/resources/view/MainWindow.fxml
Labels: UI

#100 Fix gradle issues (Urgent fix)
  build.gradle
  src/main/resources/view/FitBook.css
Labels: type.bug

#105 Branch find feature
  src/main/java/seedu/fitbook/commons/core/Messages.java
  src/main/java/seedu/fitbook/commons/util/StringUtil.java
  src/main/java/seedu/fitbook/logic/commands/AddCommand.java
  src/main/java/seedu/fitbook/logic/commands/FindCommand.java
  src/main/java/seedu/fitbook/logic/parser/FindCommandParser.java
  src/main/java/seedu/fitbook/model/client/predicate/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/AppointmentContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/CalorieContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/GenderContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/TagContainsKeywordsPredicate.java
  src/main/java/seedu/fitbook/model/client/predicate/WeightContainsKeywordsPredicate.java
  src/test/java/seedu/fitbook/commons/util/StringUtilTest.java
  src/test/java/seedu/fitbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fitbook/logic/commands/client/DeleteCommandTest.java
  src/test/java/seedu/fitbook/logic/commands/client/EditClientDescriptorTest.java
  src/test/java/seedu/fitbook/logic/commands/client/EditCommandTest.java
  src/test/java/seedu/fitbook/logic/commands/client/FindCommandTest.java
  src/test/java/seedu/fitbook/logic/commands/client/ListClientsCommandTest.java
  src/test/java/seedu/fitbook/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/fitbook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/fitbook/logic/parser/FitBookParserTest.java
  src/test/java/seedu/fitbook/model/FitBookModelManagerTest.java
  src/test/java/seedu/fitbook/model/client/predicate/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/AppointmentContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/CalorieContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/GenderContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/client/predicate/WeightContainsKeywordsPredicateTest.java
Labels: type.Enhancement, type.Task

#106 Update UG for enhanced Find
  docs/UserGuide.md
Labels: documentation

#107 Branch update schedule jh
  src/main/java/seedu/fitbook/model/client/Appointment.java
  src/main/java/seedu/fitbook/model/client/Client.java
  src/main/java/seedu/fitbook/model/client/ClientAppointmentComparator.java
  src/main/java/seedu/fitbook/model/util/SampleDataUtil.java
  src/main/java/seedu/fitbook/ui/MainWindow.java
  src/main/java/seedu/fitbook/ui/ScheduleCard.java
  src/main/java/seedu/fitbook/ui/SchedulePanel.java
  src/main/resources/view/FitBook.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleCard.fxml
  src/main/resources/view/SchedulePanel.fxml
  src/test/data/JsonSerializableFitBookTest/duplicateClientFitBook.json
  src/test/data/JsonSerializableFitBookTest/typicalClientsFitBook.json
  src/test/java/seedu/fitbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fitbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/fitbook/model/client/predicate/AppointmentContainsKeywordsPredicateTest.java
  src/test/java/seedu/fitbook/model/util/SampleDataUtilTest.java
  src/test/java/seedu/fitbook/testutil/client/TypicalClients.java
Labels: type.Enhancement, UI

#109 Enhanced Find feature to accept multiple prefix
  docs/UserGuide.md
  src/main/java/seedu/fitbook/commons/core/Messages.java
  src/main/java/seedu/fitbook/logic/commands/FindCommand.java
  src/main/java/seedu/fitbook/logic/parser/FindCommandParser.java
  src/test/java/seedu/fitbook/logic/commands/client/FindCommandTest.java
  src/test/java/seedu/fitbook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/fitbook/logic/parser/FitBookParserTest.java
Labels: type.bug, type.Enhancement

#102 Add export function
  ClientFitBook.csv
  RoutineFitBook.csv
  docs/DeveloperGuide.md
  docs/team/jundatan.md
  src/main/java/seedu/fitbook/commons/core/CsvConfig.java
  src/main/java/seedu/fitbook/logic/commands/AddCommand.java
  src/main/java/seedu/fitbook/logic/commands/ExportCommand.java
  src/main/java/seedu/fitbook/logic/commands/ExportRoutineCommand.java
  src/main/java/seedu/fitbook/logic/parser/FitBookParser.java
  src/test/java/seedu/fitbook/commons/core/CsvConfigTest.java
  src/test/java/seedu/fitbook/logic/commands/client/ExportCommandTest.java
  src/test/java/seedu/fitbook/logic/commands/client/ExportRoutineCommandTest.java
  src/test/java/seedu/fitbook/logic/parser/FitBookParserTest.java
Labels: type.Enhancement

#110 Add routines test
  src/main/java/seedu/fitbook/logic/commands/EditRoutineCommand.java
  src/main/java/seedu/fitbook/model/FitBookExerciseRoutine.java
  src/test/java/seedu/fitbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fitbook/logic/commands/routine/EditRoutineCommandTest.java
Labels: type.bug, type.Enhancement

#113 Enable assertion
  build.gradle
Labels: type.Task

#115 Branch dg draft - Darius
  docs/DeveloperGuide.md
Labels: documentation

#129 Branch update appointmentv1.3 jh
  docs/_data/projects.yml
  src/main/java/seedu/fitbook/MainApp.java
  src/main/java/seedu/fitbook/logic/parser/ParserUtil.java
  src/main/java/seedu/fitbook/model/client/Appointment.java
  src/main/java/seedu/fitbook/model/util/SampleDataUtil.java
  src/main/java/seedu/fitbook/ui/ClientCard.java
  src/main/java/seedu/fitbook/ui/HelpWindow.java
  src/main/java/seedu/fitbook/ui/ScheduleCard.java
  src/main/resources/images/weightIcon.png
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/fitbook/model/util/SampleDataUtilTest.java
Labels: type.Enhancement, priority.high, UI, severity.High

#131 Update Develop Guide
  docs/DeveloperGuide.md
Labels: documentation, priority.high, type.Task

#134 Further update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddEditRoutineState0.puml
  docs/diagrams/AddEditRoutineState1.puml
  docs/diagrams/AddEditRoutineState2.puml
  docs/diagrams/AddRoutineSequenceDiagram.puml
  docs/images/AddEditRoutineState0.png
  docs/images/AddEditRoutineState1.png
  docs/images/AddEditRoutineState2.png
  docs/images/AddRoutineSequenceDiagram.png
Labels: documentation

#136 Branch dg draft
  docs/DeveloperGuide.md
  docs/diagrams/AddExerciseSequenceDiagram.puml
  docs/diagrams/AddExerciseState0.puml
  docs/diagrams/AddExerciseState1.puml
  docs/diagrams/DeleteRoutineSequenceDiagram.puml
  docs/diagrams/DeleteRoutineState0.puml
  docs/diagrams/DeleteRoutineState1.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ExportState0.puml
  docs/images/AddExerciseSequenceDiagram.png
  docs/images/AddExerciseState0.png
  docs/images/AddExerciseState1.png
  docs/images/DeleteRoutineSeqDiagram.png
  docs/images/DeleteRoutineState0.png
  docs/images/DeleteRoutineState1.png
  docs/images/ExportSequenceDiagram.png
  docs/images/ExportState0.png
Labels: documentation

#147 Update UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/AddClientUG.png
  docs/images/EditClientUG.png
  docs/images/Ui.png
  src/main/java/seedu/fitbook/model/client/Calorie.java
Labels: documentation

#145 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterFitBookExerciseRoutineModelClassDiagram.puml
  docs/diagrams/BetterFitBookModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterFitBookExerciseRoutineModelClassDiagram.png
  docs/images/BetterFitBookModelClassDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FitBookBanner.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#148 Update UG
  docs/UserGuide.md
Labels: documentation

#150 Update UG
  docs/UserGuide.md
Labels: documentation

#152 Update UG
  docs/UserGuide.md
Labels: documentation

#153 Update UG
  docs/UserGuide.md
Labels: documentation

#154 Branch update ug
  docs/UserGuide.md
Labels: documentation

#151 Add addWeight command and graph command to UG
  docs/UserGuide.md
Labels: documentation, priority.high

#159 Bug with missing view command and edit exercise routine not functioning as expected for storage
  ClientFitBook.csv
  src/main/java/seedu/fitbook/logic/commands/EditRoutineCommand.java
  src/main/java/seedu/fitbook/logic/commands/ViewDetailCommand.java
  src/main/java/seedu/fitbook/logic/parser/FitBookParser.java
  src/main/java/seedu/fitbook/model/client/Client.java
  src/main/java/seedu/fitbook/model/routines/Routine.java
  src/main/java/seedu/fitbook/ui/SummaryCard.java
  src/main/resources/view/SummaryCard.fxml
Labels: type.bug

#162 Fix issues with wrap text and weight class to add range
  ClientFitBook.csv
  src/main/java/seedu/fitbook/model/client/Weight.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ExerciseCard.fxml
  src/main/resources/view/ExerciseListCard.fxml
  src/main/resources/view/ScheduleCard.fxml
  src/main/resources/view/SummaryCard.fxml
  src/main/resources/view/SummaryListCard.fxml
  src/test/java/seedu/fitbook/model/client/WeightTest.java
  src/test/java/seedu/fitbook/testutil/client/ClientBuilder.java
Labels: type.bug
